name: ultimate_extension
description: Ultimate_extension provides powerful extensions for Dart collections and objects, enabling advanced data manipulation and simpler coding."
version: 1.0.0
repository: https://github.com/Oauth-Celestial/ultimate_extension

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
